import random


class Pickup:
    def __init__(self):
        self.list = ['I am going to complain to Spotify about you not being this weeks hottest single.',
                     'Do you have a map? Because I just keep getting lost in your eyes!',
                     'Your hand looks heavy can i hold it for you?',
                     'Roses are red, my face is too, that only happens when I’m around you',
                     'Your lips look lonely would they like to meet mine?',
                     'Hi my name is _______, remember it, cause you’ll be screaming it all night',
                     'Can I have your picture so I can show Santa what I want for Christmas?',
                     'My dick is so polite… it stands up so you can sit down.',
                     'Let’s commit the perfect crime: I’ll steal your heart, and you’ll steal mine.',
                     'Are you a camera? Because every time I look at you, I smile.',
                     'Do you have a name or can I call you mine?',
                     'If I was a chessboard, I’d be lucky to have a queen like you',
                     'Are you a camera because you make me smile',
                     'Can I use your phone? My mom told me to call her once I found the girl of my dreams',
                     'If I ever freeze, don’t think that it’s because of a computer virus. '
                     'It’s probably because I was stunned by your beauty.',
                     'Are you from Russia? Cuz you’re Russian my heart rate!',
                     'Do you have a BandAid? I just scraped my knee falling for you',
                     'Do you like sleep? Same, we should do it together sometime',
                     'Are you my geometry teacher? Because from this angle you look very acute',
                     'I think my perfect menu would include you.',
                     'Forget the butterflies; I get the whole zoo when I see you.',
                     'Roses are red\nviolets are blue\nthere isn’t a star,\nas sparkling as you',
                     'Are you http? Because without you I’m :////',
                     'If there wasn\'t gravity on Earth, I’d still fall for you',
                     'Knock knock\nwho’s there\nbaby yoda\nbaby yoda who\nbaby yoda only one for me',
                     'If I flip a coin what are the chances I get head',
                     'Are you a chicken? Because you’re impeccable',
                     'Are you the finish line? Because you’re endgame to me',
                     'Do you like science? Because I’ve got my ion you',
                     'Are you Ariel? Because we Mermaid for each other',
                     'Are you a quart of sugar? Because you are 1 sweet qt',
                     'Are you a bank loan? Because you have my interest',
                     'Can you tie my shoes? I don’t want to fall for anyone else',
                     'If you were a virus you would be CUTIE-19',
                     'Tell me you are a banana because I find you a peeling',
                     'Hi my name is _______ but you can call me anytime',
                     'Are you a mountain? Cos I wanna get on top of you.',
                     'Are you religious?\nCause you’re the answer to all my prayers.',
                     'Can I have directions?\nTo where?\nTo your heart.',
                     'How much will $20 get me?',
                     'How is your fever?\nWhat fever?\nOh… you just look hot to me.',
                     'Do you have a sunburn, or are you always this hot?',
                     'People are catching Coronavirus but the only thing I’m catching is feelings for you.',
                     'If being in love was illegal, will you be my partner in crime?',
                     'I’m going to the optometrist to get my eyes checked.'
                     ' For some reason, I can’t take them off of you.',
                     'I would say ‘God bless you,’ but it seems like he already did.',
                     'If I could just rearrange the alphabet, I would definitely put ‘U’ and ‘I’ together.',
                     'My future children need your DNA!',
                     'Damn, girl, your bone structure is giving my bone structure',
                     'I’m gonna tap my nutsack on your buttcrack',
                     'Are you the Capital Building?\nCause I\'ll get 10 years for coming inside you',
                     'There\'s a sale at my house\nClothes are 100% off',
                     'I shit my pants\nCan I get in yours?',
                     'Are you a motorcycle accident?\nCause I\'m going head over heels for you',
                     'I lost my number. Can I have yours?',
                     'Are you suicide?\nCause you\'ve been on my mind all day',
                     'Are you a coconut?\nCause I\'m gonna smash you until white stuff comes out',
                     'Are you the South?\nCause I\'m gonna send my troops down there',
                     'Are you a mirror?\nCause I see myself inside you',
                     'Do you have Amazon Prime?\nCause I have a package to deliver',
                     'Are you an elevator?\nCause you elevate my whole life',
                     'I\'ve had a shitty day. But you made it better :)',
                     'If my life were a puzzle, you would be my missing piece.',
                     'You look tired. Need a shoulder to rest your legs on?',
                     'I like my bed, but I’d rather be in yours.',
                     'Are you an army general? Because you’re having my privates standing at attention.',
                     'Damn, you shit with that ass?',
                     'I would never play hide and seek with you because someone like you is impossible to find.',
                     'Are you a DBD killer? Because you got me hooked.',
                     'I’m not an organ donor but I’d give you my heart anytime',
                     'I’m not a weatherman, but you can expect a few more inches tonight',
                     'If it’s raining out right now, can we go make out in the rain so you can make me get wet twice?',
                     'You look like an extremely hard worker and I have an opening that you can fill.',
                     'Getting very confused hearing my name over and over again and you’re not out of breath',
                     'They said I should take vitamin D, maybe I’m stuffing it in the wrong hole. Want to help me?',
                     'Do I have to sign for your package?',
                     'Are you drowning? Because I’m feeling the urge to give you CPR',
                     'I love you with all of my circle, not my heart. Because hearts break, but circles go on forever',
                     'I know you’re not a poke stop but I’d still spin you around and tap that',
                     'I’ve lost my teddy bear! Can I sleep with you instead?',
                     'I’m just trying to find a reason to use the carpool lane. Can you help me?',
                     'My pronouns are I/am/yours. What are yours?',
                     'Is your name epinephrine? Because you make my heart race.',
                     'It’s pull day and the only thing I want to pull today is you.',
                     'Are you a Little Caesar’s pizza? Because you’re hot and I’m ready.',
                     'If I were president, I’d make you my First Lady.',
                     'Are you the Taliban, because you could terrorize me for 20 years'
                     ' and I’d still fall for you in 1 day',
                     'I’m gonna need you to hand over your driver’s license because I’ve '
                     'received numerous reports from people about how you’re driving them crazy',
                     ' Are you a toaster? Because I’d love to take a bath with you.',
                     'I was going to offer to paint you but you’re clearly already a work of art',
                     'Are you religious? Because you’re the answer to all of my prayers',
                     'I heard you\'re looking for a stud\nWell I have an STD and all I need is u',
                     'Do you watch Haikyuu? Because I kinda laikyuu',
                     'Call me Jeffrey Dahmer. Cause you\'re lookin like snack rn',
                     'Are you mixed? Because you look half fine half mine',
                     'I saw your partner today, I went to hug them but I bumped into the mirror',
                     'What’s the difference between you and history? History is the past, you’re my future.',
                     'The world’s longest kiss lasted for 58 hours. 35 minutes, and 58 seconds. '
                     'Do you wanna beat a world record with me?',
                     'I’m about to hit the lottery right now. How? Your ten digits right now.',
                     'If you were a vegetable, you’d be a \'cute-cumber.\'',
                     'Are you an electrician? Because you’re definitely lighting up my day']

    def regular(self):
        return self.list[random.randint(0, len(self.list) - 1)]
